language: node_js
node_js:
  - stable
install:
  # not compatible webpack@3.1.0 and extract-text-webpack-plugin@2.1.2
  - npm install --force
script:
  - npm run lint
  - npm run test
  - npm run coverage
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
